//
//  AutoGeneratedDB.swift
//  CarRescue
//
//  Created by jacky nguyen on 4/10/16.
//  Copyright © 2016 jackyCode.com. All rights reserved.
//

import Foundation
import Parse

class AutoGeneratedDB {
    class func createData () {
        let store = PFObject(className: "stores")
        
        store["store_name"] = "test name"
        store["location"]   = PFGeoPoint(latitude: 1.2, longitude: 3.4)
        
        store["store_avatar"] = "trung"
        
        store.saveInBackgroundWithBlock { (success:Bool, error:NSError?) -> Void in
            if success {
                print("done")
            } else {

            }
        }
    }
    
    class func signUp() {
        let user = PFUser()
        user.username = "trung"
        user.password = "aaaa"
        user.email = "email@example.com"
        // other fields can be set just like with PFObject
        user["phone"] = "415-392-0202"
        
        user.signUpInBackgroundWithBlock {
            (succeeded: Bool, error: NSError?) -> Void in
            if let error = error {
                let errorString = error.userInfo["error"] as? NSString
                // Show the errorString somewhere and let the user try again.
                print(errorString)
            } else {
                // Hooray! Let them use the app now.
                print("sign up success full")
            }
        }
    }
    
    
    class func login() {
        PFUser.logInWithUsernameInBackground("trung", password:"aaaa") {
            (user: PFUser?, error: NSError?) -> Void in
            if user != nil {
                // Do stuff after successful login.
            } else {
                // The login failed. Check error to see why.
            }
        }
    }
   
    
    
}
