//
//  ViewController.swift
//  CarRescue
//
//  Created by DEREK DO on 6/4/16.
//  Copyright © 2016 jackyCode.com. All rights reserved.
//

import UIKit
import Parse

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        //AutoGeneratedDB.createData()
        //AutoGeneratedDB.signUp()
        //AutoGeneratedDB.login()
        
        //print(PFUser.currentUser())
        
        /*if let currentUser = PFUser.currentUser() {
            currentUser["userAvatar"] = "https://cdn.photographylife.com/wp-content/uploads/2014/06/Nikon-D810-Image-Sample-6.jpg"
            currentUser.saveInBackground()
        }*/
        
        // create event
        
        let event = PFObject(className:"Events")
        
        event["userId"] = PFUser.currentUser()
        
        event["location"] = PFGeoPoint(latitude: 1.222, longitude: 1.222)
        
        event["type"]  = "Gas"
        
        event.saveInBackground()
    }
    
    

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}

